version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - cd monolith-web-app && mvn package
      - echo Copiando al bucket $S3_ARTIFACT_BUCKET
      - tar -czvf monolith-web-app.tar.gz target/monolith-web-app.war appspec.yaml ../scripts/*
      - aws s3 cp monolith-web-app.tar.gz s3://$S3_ARTIFACT_BUCKET/
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - monolith-web-app/monolith-web-app.tar.gz
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'