version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - cd monolith-web-app && mvn package
      - cd .. && mv monolith-web-app/target/monolith-web-app.war monolith-web-app.war
      - zip -ur monolith-web-app.zip monolith-web-app.war appspec.yml scripts
      - aws s3 cp monolith-web-app.zip s3://$S3_ARTIFACT_BUCKET/
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - monolith-web-app.zip
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'