spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:    url: jdbc:mysql://localhost:3306/webappevolution
    username: webappevolution_user
    password: Lunes123
    initialization-mode: embedded
